// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3nFWf3c1iOOFVzppkd5u5eJmHFTQKiVQ',
    appId: '1:957567461853:web:56d9fe7bf9cd11bf442e34',
    messagingSenderId: '957567461853',
    projectId: 'southend-safe-watch',
    authDomain: 'southend-safe-watch.firebaseapp.com',
    storageBucket: 'southend-safe-watch.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg-5L5u34duYfKx5kW9KFQEJmiYudWFjs',
    appId: '1:957567461853:android:afa5974069ef671a442e34',
    messagingSenderId: '957567461853',
    projectId: 'southend-safe-watch',
    storageBucket: 'southend-safe-watch.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKE2PMx3JXnIIzV_X-WnZyGGQVuOrX5Z8',
    appId: '1:957567461853:ios:c2be967657ab6eb5442e34',
    messagingSenderId: '957567461853',
    projectId: 'southend-safe-watch',
    storageBucket: 'southend-safe-watch.firebasestorage.app',
    iosBundleId: 'com.example.safewatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3nFWf3c1iOOFVzppkd5u5eJmHFTQKiVQ',
    appId: '1:957567461853:web:f82c6a917836b0d6442e34',
    messagingSenderId: '957567461853',
    projectId: 'southend-safe-watch',
    authDomain: 'southend-safe-watch.firebaseapp.com',
    storageBucket: 'southend-safe-watch.firebasestorage.app',
  );

}